### ISSUE TITLE
Format error in output CIF

### ISSUE THREAD

**Issue by mf-rug** [PDB-REDO/alphafill#11]
Hello, thanks for making this nice tool. One issue: if I open the output .cif file in YASARA, I get this error:

`LoadCIF AF-A0A0D5XX59-F1-model_v3_filled - ERROR - The (mm)CIF file could not be parsed successfully, C4A PLP 1 B is present in the bond section (_struct_conn), but not in the atom coordinate section (_atom_site)`

I get this error every time, no matter the structure or ligands in there. Yasara is apparently being a bit very picky here, since it's not a problem to open the file e.g. in PyMol or ChimeraX. If I open the file in chimera and save it as pdb, I can also open it in Yasara, no problem. Presumably, chimera fixes the problem automatically and saves in the correct format. In any case, I thought I'd report this and maybe you can have a look if there is a bug in how you write the output cif.

Additional info:
Yasara version: 22.8.22 (bug occurs on linux and MacOS version)
ChimeraX version:  1.5.dev202207171906

**Comment by drlemmus** [comment]
We will investigate. Judging from the accession code, it seems that you made this model with a local copy of the AlphaFill software. Is that correct?
Do you also have this issue with files you download from the databank?

**Comment by mf-rug** [comment]
Local build, correct, sorry, should have mentioned that. Just checked, same error occurs for structures downloaded from the database:

`>Loadcif "~/Downloads/AF-Q0G9W6-F1-model_v1.cif" - ERROR - The (mm)CIF file could not be parsed successfully, MN4 OEY 1 DG is present in the bond section (_struct_conn), but not in the atom coordinate section (_atom_site).`

**Comment by mhekkel** [comment]
Although I agree the files created by alphafill are not completely flawless, the error you describe is in fact an error in Yasara and not in alhpafill. The atom Yasara complains about is actually really present.
