### ISSUE TITLE
Running AlphaFill locally on one's own AlphaFold models

### ISSUE THREAD

**Issue by eric-jm-lang** [PDB-REDO/alphafill#13]
Hello,

Thank you for this very interesting tool. 

Something is not clear to me: if I install AlphaFill locally (along with PDB-REDO or PDB in mmCIF format and the associated fasta file), can I then use it to transplant co-factors and ions on my own AlphaFold models (i.e. without any Uniprot ID)?

If so, what sort of command should I run? I am not sure to understand what the `alphafill /srv/data/afdb/cif/AF-XXX.cif.gz /srv/data/af-filled/AF-XXX.cif.gz` command do.

Many thanks in advance for your help.

**Comment by mhekkel** [comment]
Sssh, don't tell anyone, but you can now upload your own sequences to https://alphafill.eu/test/

That upload feature will be publicly available soon.

But to answer your question, yes, you can build and run alphafill locally. The example command you quote is taking an input file and output file as parameters. The rest of the options are inside a config file.

You can run alphafill --help to see what the other options are.
