### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by WillExeter** [PDB-REDO/alphafill#14]
Hey Robbie, 

Long time! Trying to install AlphaFill (Ubuntu 20.04) as an add on to our AlphaFold server but running into issues with libcif++ when building. The git clone was installed but seemed to be lacking the structure.hpp file. Which version of libcif++ should be used when installing? 

Beste, 
Will Stuart

**Comment by mhekkel** [comment]
The code in the trunk of the alphafill github repository is out of sync with libcifpp. You can try to use the develop branch from alphafill with the trunk version of libcifpp. Or you should install an earlier version of libcifpp, one of the 4.x tagged versions.
