### ISSUE TITLE
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by jeromeRlon** [PDB-REDO/alphafill#16]
A problem of the website, probably a bug. 

When I upload a pdb file, which works in other websites, the "https://alphafill.eu/" reported this: 

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by drlemmus** [comment]
Hmm, that is something that needs investigation. Can you share your pdb file with us? You can share it in confidence to r.joosten_At_nki.nl

**Comment by mhekkel** [comment]
No need to send that file, I screwed up in the new version of libzeep. Should be fixed now.
