### ISSUE TITLE
[Question] How to get the FastA formatted file for all sequences in this databank?

### ISSUE THREAD

**Issue by agdiaz** [PDB-REDO/alphafill#17]
Hello everyone there, thank you very much for this tool!

I'm trying to install it locally and after installing all the dependencies, now I'm about to run the command:

```
alphafill prepare-pdb-list --pdb-dir=${PDB_DIR} --pdb-fasta=${PDB_FASTA} --output pdb-id-list.txt
```

I've downloaded the PDB-REDO entire DB using the `rsync` command. My question is how to get the FASTA file. Do you have a link to provide me to continue with the configuration? Or a method to extract the FASTA files from the PDB-REDO DB?

Thanks in advance for your help!

Best regards from Brussels,

**Comment by mhekkel** [comment]
If you've downloaded the entire pdb-redo databank, you can find the file in the _others_ directory, it is named pdbredo_seqdb.txt

I believe we should add this bit to the documentation.

**Comment by agdiaz** [comment]
Thanks for the info @mhekkel ! Agree with the idea of adding it to the Readme file 👍
