### ISSUE TITLE
UNL ligand crash

### ISSUE THREAD

**Issue by mf-rug** [PDB-REDO/alphafill#19]
Hi,

might this be a bug? In one of the structures I'm trying to fill alphafill just aborts after this:

```
Error when processing 3f0h for nohd
 >> Trying to insert unknown compound UNL (not found in CCD)
```

in structure [3f0h](https://www.rcsb.org/structure/3F0H), there is indeed an unknown ligand (UNL) annotated ([looks a bit like a mistake in that case](https://www.rcsb.org/3d-view/3F0H?preset=ligandInteraction&label_asym_id=B))
As UNL is of course not an actual ligand, it seems like a more appropriate behaviour would be to ignore UNLs? At least it shouldn't crash.

**Comment by mhekkel** [comment]
UNL is a valid entry in components.cif. You reported before that your components.cif is not installed properly, hence this error stems from that issue. Please try to install components.cif and you'll notice this error is gone.

**Comment by mf-rug** [comment]
How does it make sense that [UNL](https://www.rcsb.org/ligand/UNL) is a valid entry? It's not a defined molecule, always a different one depending on the structure. Which of the [461 different UNLs](https://www.rcsb.org/search?request=%7B%22query%22%3A%7B%22type%22%3A%22group%22%2C%22nodes%22%3A%5B%7B%22type%22%3A%22group%22%2C%22nodes%22%3A%5B%7B%22type%22%3A%22group%22%2C%22logical_operator%22%3A%22and%22%2C%22nodes%22%3A%5B%7B%22type%22%3A%22terminal%22%2C%22service%22%3A%22text%22%2C%22parameters%22%3A%7B%22attribute%22%3A%22rcsb_nonpolymer_instance_feature_summary.comp_id%22%2C%22operator%22%3A%22exact_match%22%2C%22value%22%3A%22UNL%22%7D%7D%2C%7B%22type%22%3A%22terminal%22%2C%22service%22%3A%22text%22%2C%22parameters%22%3A%7B%22attribute%22%3A%22rcsb_nonpolymer_instance_feature_summary.type%22%2C%22operator%22%3A%22exact_match%22%2C%22value%22%3A%22HAS_COVALENT_LINKAGE%22%7D%7D%2C%7B%22type%22%3A%22terminal%22%2C%22service%22%3A%22text%22%2C%22parameters%22%3A%7B%22attribute%22%3A%22rcsb_nonpolymer_instance_feature_summary.count%22%2C%22value%22%3A0%2C%22operator%22%3A%22equals%22%7D%7D%5D%7D%5D%2C%22logical_operator%22%3A%22and%22%2C%22label%22%3A%22text%22%7D%5D%2C%22logical_operator%22%3A%22and%22%7D%2C%22return_type%22%3A%22entry%22%2C%22request_options%22%3A%7B%22paginate%22%3A%7B%22start%22%3A0%2C%22rows%22%3A25%7D%2C%22results_content_type%22%3A%5B%22experimental%22%5D%2C%22sort%22%3A%5B%7B%22sort_by%22%3A%22score%22%2C%22direction%22%3A%22desc%22%7D%5D%2C%22scoring_strategy%22%3A%22combined%22%7D%2C%22request_info%22%3A%7B%22query_id%22%3A%2254d2982f6afec8ed878768656ed809ee%22%7D%7D) in the pdb is in components.cif?
Also, why does alphafill crash for me only for this ligand and works fine for the rest? (I installed libcifpp according to the instructions, and I have copied components.cif in the dirs you indicated in the other thread)

**Comment by mhekkel** [comment]
components.cif contains:

```
data_UNL
#

_chem_comp.id                                   UNL
_chem_comp.name                                 "Unknown ligand"
_chem_comp.type                                 NON-POLYMER
_chem_comp.pdbx_type                            HETAIN
_chem_comp.formula                              ?
_chem_comp.mon_nstd_parent_comp_id              ?
_chem_comp.pdbx_synonyms                        ?
_chem_comp.pdbx_formal_charge                   0
_chem_comp.pdbx_initial_date                    2008-04-10
_chem_comp.pdbx_modified_date                   2008-12-05
_chem_comp.pdbx_ambiguous_flag                  Y
_chem_comp.pdbx_release_status                  REL
_chem_comp.pdbx_replaced_by                     ?
_chem_comp.pdbx_replaces                        ?
_chem_comp.formula_weight                       ?
_chem_comp.one_letter_code                      ?
_chem_comp.three_letter_code                    UNL
_chem_comp.pdbx_model_coordinates_details       ?
_chem_comp.pdbx_model_coordinates_missing_flag  N
_chem_comp.pdbx_ideal_coordinates_details       ?
_chem_comp.pdbx_ideal_coordinates_missing_flag  N
_chem_comp.pdbx_model_coordinates_db_code       ?
_chem_comp.pdbx_subcomponent_list               ?
_chem_comp.pdbx_processing_site                 RCSB
##
```

And crashing is a bit harsh. It stops and tells you that UNL is not found in the CCP4 monomers library. Which is correct. If you had components.cif, the program would have continued.

Question, did you specify a CMAKE_INSTALL_PREFIX when building libcifpp? If so, the library is using that as location for the data files it is looking for.

**Comment by mf-rug** [comment]
I didn't specify CMAKE_INSTALL_PREFIX. But the [libcifpp](https://github.com/PDB-REDO/libcifpp) site says "The default is to install everything in $HOME/.local on Linux ", which is also where the components.cif is in my case: `~/.local/share/libcifpp/components.cif`

```
$ grep -A 27 data_UNL ~/.local/share/libcifpp/components.cif
data_UNL
#

_chem_comp.id                                   UNL
_chem_comp.name                                 "Unknown ligand"
_chem_comp.type                                 NON-POLYMER
_chem_comp.pdbx_type                            HETAIN
_chem_comp.formula                              ?
_chem_comp.mon_nstd_parent_comp_id              ?
_chem_comp.pdbx_synonyms                        ?
_chem_comp.pdbx_formal_charge                   0
_chem_comp.pdbx_initial_date                    2008-04-10
_chem_comp.pdbx_modified_date                   2008-12-05
_chem_comp.pdbx_ambiguous_flag                  Y
_chem_comp.pdbx_release_status                  REL
_chem_comp.pdbx_replaced_by                     ?
_chem_comp.pdbx_replaces                        ?
_chem_comp.formula_weight                       ?
_chem_comp.one_letter_code                      ?
_chem_comp.three_letter_code                    UNL
_chem_comp.pdbx_model_coordinates_details       ?
_chem_comp.pdbx_model_coordinates_missing_flag  N
_chem_comp.pdbx_ideal_coordinates_details       ?
_chem_comp.pdbx_ideal_coordinates_missing_flag  N
_chem_comp.pdbx_model_coordinates_db_code       ?
_chem_comp.pdbx_subcomponent_list               ?
_chem_comp.pdbx_processing_site                 RCSB
##
```
