### ISSUE TITLE
Error building AlphaFill on Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by Vedasheersh** [PDB-REDO/alphafill#21]
Hi,

Great work on AlphaFill, this is really helping with some large-scale structure-function studies we always wanted to do. I am not much of a computer guy, but I am trying to use alphafill as a part of my PhD. I would greatly appreciate your help!

I am trying to build alphafill on Ubuntu 20.04.5 LTS using cmake. I followed the instructions in README.md step by step. I encounter the following error. Any idea why this error comes up and how to fix this?
```
ubuntu@xx:~/alphafill_code/alphafill/build$ sudo cmake --build .
Scanning dependencies of target webpack
[  6%] Generating ../docroot/scripts/index.js
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
make[2]: *** [CMakeFiles/webpack.dir/build.make:67: ../docroot/scripts/index.js] Error 1
make[1]: *** [CMakeFiles/Makefile2:888: CMakeFiles/webpack.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

Thanks,
Veda.

**Comment by mhekkel** [comment]
Hi Veda,

Did you install yarn? The one from https://yarnpkg.com/

**Comment by Vedasheersh** [comment]
Hi @mhekkel 

Thank you so much for your quick response!

Yes, I had installed yarn using node.js and figured the binary is named 'node.yarn'. I now created a symbolic link to this as '/usr/bin/yarn' and run the setup again. It worked!

Thanks a lot!

Veda.
