### ISSUE TITLE
Alphafill usage

### ISSUE THREAD

**Issue by lukab86** [PDB-REDO/alphafill#23]
Can you please write an example of usage case of alphafill with all necessary steps, how should it be used to determine ion positions in a protein structure created by AlphaFold? Also, how should alphafill.conf look like, and how big is the database that needs to be downloaded?
Thank you in advance.

**Comment by drlemmus** [comment]
You need to get the pdb-redo databank that is close to 2 TB although you can leave out a lot of data to reduce the size. If you are looking for a quick solution, it's best to use the upload function on alphafill.eu

**Comment by lukab86** [comment]
Thank you very much for the quick response. But in case of the local usage, can you please provide a real life example, how would I add metal ions to an AlphaFold PDB structure including the config file and a proper Alphafill command?

**Comment by drlemmus** [comment]
The Readme has a description of the commands to run. You can add the following to the config file:

pdb-fasta=/DATA/pdb-redo/others/pdbredo_seqdb.txt
pdb-dir=/DATA/pdb-redo/
ligands=/DATA/af-ligands.cif
pdb-id-list=/DATA/pdb-id-list.txt
