### ISSUE TITLE
rsync download of the PDB-REDO DB not working

### ISSUE THREAD

**Issue by roger-boop** [PDB-REDO/alphafill#26]
I am not 100% sure that this is the right place for asking this, but I am trying to download the PDB-REDO DB for running alphafill.
I am using the command on the webpage 'rsync -av rsync://rsync.pdb-redo.eu/db/ pdb-redo/'
This are the errors I get:
rsync: [Receiver] failed to connect to rsync.pdb-redo.eu (192.87.97.253): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(137) [Receiver=3.2.3]

I am on ubuntu 22.04.1

If the rsync server is no longer running could you give an alternative to download the DB?

**Comment by mhekkel** [comment]
That URL should have been rsync://rsync.pdb-redu.eu/pdb-redo/

So the command should be:

rsync -av rsync://rsync.pdb-redo.eu/pdb-redo/ pdb-redo/

I will update the web page. Thanks for reporting

**Comment by roger-boop** [comment]
Hi again. This URL still gives me the same error, it is possible that I'm doing something wrong? I simply open the terminal, cd to the directory where I want to store the data, and execute the command.
Thanks for the fast answer

**Comment by mhekkel** [comment]
Most likely you are sitting behind a firewall that blocks access to our rsync server. Please contact your local service desk for help since the command given should really work.
