### ISSUE TITLE
Installation in docker

### ISSUE THREAD

**Issue by Nick-Mul** [PDB-REDO/alphafill#27]
Hello, this program looks really useful but all this C stuff is making me feel a bit of an idiot ;) ! 

I seem to be running into a few problems with the mrc install, and in the final sets of the alphafill build.

I would be very grateful for any tips you had to get this working, my ugly Dockerfile is below! 

Best regards,
Nick 

root@f395d95b5b9d:~/alphafill/build# cmake .. -DCMAKE_BUILD_TYPE=Release
Using resources compiled with /usr/local/bin/mrc
CMake Error at CMakeLists.txt:101 (find_package):
  By not providing "Findzeep.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "zeep", but
  CMake did not find one.

  Could not find a package configuration file provided by "zeep" (requested
  version 5.1.8) with any of the following names:

    zeepConfig.cmake
    zeep-config.cmake

  Add the installation prefix of "zeep" to CMAKE_PREFIX_PATH or set
  "zeep_DIR" to a directory containing one of the above files.  If "zeep"
  provides a separate development package or SDK, be sure it has been
  installed.

```
 FROM ubuntu:20.04
 
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update ; apt upgrade -y ; apt-get -y install build-essential \
 git \
 cmake \
 wget \
 libzeep-dev \
 libc++1 \
 libpq-dev \
 libpqxx-dev \
 zlib1g-dev \
 curl

WORKDIR /root/
RUN git clone https://github.com/mhekkel/libmcfp.git; \
    cd libmcfp \
    mkdir build \
    cd build; \
    cmake .. \
    cmake --build . \
    cmake --install .

WORKDIR /root/
RUN git clone https://github.com/mhekkel/mrc.git; \
    cp -r libmcfp mrc; \
    cd mrc; \
    mkdir build; \
    cd build; \
    cmake .. \
    cmake --build . \
    cmake --install .

WORKDIR /root/
RUN git clone https://github.com/PDB-REDO/libcifpp.git; \
    cd libcifpp; \
    cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release; \
    cmake --build build; \
    cmake --install build


RUN apt remove yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get -y install yarn

RUN curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
RUN sh /tmp/nodesource_setup.sh
RUN apt install -y nodejs

RUN git clone https://github.com/PDB-REDO/alphafill; cd alphafill; yarn;
    mkdir build;\ cd build; cmake .. -DCMAKE_BUILD_TYPE=Release; \
    cmake --build .\
```

**Comment by huiwenke** [comment]
Here is an available docker image for v1.2.1: https://hub.docker.com/r/230218818/alphafill. Please note the versions of dependencies.

**Comment by Nick-Mul** [comment]
What an elegant Dockerfile, thank you so much.

**Comment by Yang-Wang-2020** [comment]
Thank you so much for the dockerfile!!!!
