### ISSUE TITLE
Where are the selection of chemical compounds stored?

### ISSUE THREAD

**Issue by r-krishna** [PDB-REDO/alphafill#28]
Hello, thank you for this great work!

In your paper, I noticed "The current collection of compounds to be transplanted consists of 2,694 entries. It is stored separate from the AlphaFill program to allow easy extension in future incarnations of the AlphaFill databank and is freely available." 

Could you point me to where these are located? 

Thank you!

**Comment by huiwenke** [comment]
https://alphafill.eu/compounds
Maybe their detailed information is in `/usr/local/share/libcifpp/components.cif`? The file can be downloaded from ftp://ftp.wwpdb.org/pub/pdb/data/monomers/components.cif.gz.

**Comment by mhekkel** [comment]
The set of transplantable ligands is recorded in the file af-ligands.cif. You can find the default one here:

https://github.com/PDB-REDO/alphafill/blob/trunk/af-ligands.cif

If you build the software yourself, you can specify this file using a command line switch.
