### ISSUE TITLE
Remove mrc dependency from alphafill

### ISSUE THREAD

**Issue by YoshitakaMo** [PDB-REDO/alphafill#34]
Related to https://github.com/mhekkel/mrc/issues/12, if it's possible to remove `mrc` dependency from alphafill, it's anticipated that the alphafill package will become accessible through macOS Homebrew, facilitating broader experimentation for many researchers.
I would appreciate your consideration of this proposal.

**Comment by mhekkel** [comment]
I agree, it took some time. But I finally released a new version of alphafill that should work on macOS as well.
