### ISSUE TITLE
Error when processing 2ONG for nohd >> max-ligand-to-polymer-atom-distance: unknown option

### ISSUE THREAD

**Issue by eporetsky** [PDB-REDO/alphafill#39]
I get the following error after running a structure I predicted with the alphafold2 colabfold notebook:
Error when processing 2ONG for nohd >> max-ligand-to-polymer-atom-distance: unknown option
JobID: https://alphafill.eu/model?id=CS-39a097880b28c8d35ce46ad6d78e42d18429a69b

Below is the uploaded PDB file (renamed to.txt so I can upload it)
[2ONG_colabfod_af2.txt](https://github.com/PDB-REDO/alphafill/files/13852124/2ONG_colabfod_af2.txt)

The protein sequence I used to generate the predicted structures is the same as the 2ONG experimental structure that seems to be in the error message. I tried running the experimental PDB and a AF2 colabfold-predicted PDB of the example sequence and both ran successfully so I wonder if this might be an issue (uncommon) on the AlphaFill side?

Let me know if there is any additional information I can provide.
Thank you for the help!

**Comment by mhekkel** [comment]
This should now be fixed. Finally.
