### ISSUE TITLE
"Query should have returned exactly one row" Error

### ISSUE THREAD

**Issue by DamienWaits** [PDB-REDO/alphafill#40]
I'm using Alphafill to process multiple cif files from Omegafold and I'm running into the following error for some of my inputs.

Error when processing 4CW2 for LCL|AL009126
 >> query should have returned exactly one row

I've download the pdb-repo with 'rsync -av rsync://rsync.pdb-redo.eu/db/ pdb-redo/'

This is occurring in a very small amount of sequences, 19 out of ~5000.

Is this issue likely arising from the sequence or cif file? Or could it be the pdb reference file is missing/configured incorrectly?

**Comment by mhekkel** [comment]
First obvious question: is your components.cif file up-to-date? When installing libcifpp you have the option to install an update script to keep this file in sync with upstream. You still have to edit the config file for this to enable automatic updates.

See: https://www.hekkelman.net/libcifpp-doc/compound.html

But if that's ok, you might want to send me a file to test with.

**Comment by DamienWaits** [comment]
Seems that was my issue.  I ran the update script manually, and I reconfigured libcifpp to install the update script and reconfigured and reinstalled alphafill. I am no longer receiving the error and the runs are finishing.
