### ISSUE TITLE
Warning: Missing atom for atom ID

### ISSUE THREAD

**Issue by DamienWaits** [PDB-REDO/alphafill#41]
I am receiving warnings like the following during some of my Alphafold runs on Omegafold output:

`3ZW9`
`Missing atom for atom ID OAP`

The offending lines from my cif look like:

`HETATM 5006 O  OAP B COA BV 3    . ?   7.041  15.430   9.293 0.30 154.79 ? 1   COA BV OAP 1`

Alphafill is completing successfully but some inputs throw warnings like this for multiple atoms and I'm curious if the output will likely be affected.

Pdb-repo downloaded with 'rsync -av rsync://rsync.pdb-redo.eu/db/ pdb-redo/'

**Comment by drlemmus** [comment]
Sometimes an atom is missing in the experimental model that can trigger such a warning. If there are more experimental models with the same compound the most complete one is taken. In your case the COA seems to have been transplanted from a different model. The occupancy is 0.30 which none of the parent molecules in 3zw9 have.
