### ISSUE TITLE
Error reading file

### ISSUE THREAD

**Issue by AlessioDelConte** [PDB-REDO/alphafill#43]
Hello,

I am testing the alphafill software installed locally and I have some issue running it on a cif file. I've tried to run it on a mmCIF file downloaded from the PDB and it works just fine. Then I wanted to isolate a chain from the structure using PyMOL and then re-exporting the structure in another cif.
At this point when I run `alphafill process` on the newly exported structure it outputs this error:
```
alphafill process --verbose --config=/etc/alphafill.conf /home/alessio/3vn3_A.cif /home/alessio/test_A.cif
Error reading file /home/alessio/3vn3_A.cif
 >> map::at
```

without any detailed info about why the error happens.
I think it could be related to the fact that when exporting the structure in the cif file I only have a very short header  and the atom_site table (see attached figure). Are there some mandatory tables for alphafill to work maybe?

![image](https://github.com/PDB-REDO/alphafill/assets/15822575/bfcffa87-70a6-46b4-8434-b967121f395c)

Thank you,
Alessio

**Comment by drlemmus** [comment]
I think PyMOL has brutalised your mmCIF file to the point that AlphaFill won't use it. If you want to just work on chain, A you can delete all _atom_site records that refer to other chains with a text editor. I did just that and here is the result: https://alphafill.eu/model?id=CS-24925dcf59965334e32907be5183b35f2502f6c8&identity=25
