### ISSUE TITLE
Yasara ERRoR when analysis interactions between proteins and small molecules

### ISSUE THREAD

**Issue by lightcone233** [PDB-REDO/alphafill#46]
I encountered a problem when using YASARA to calculate hydrogen bonds, PIPI bonds, ca-pi bonds and saltbrige between proteins and small molecules. 
My yasara version is: 22.5.22.
 The command I used is: yasara -txt ./md_analyze.mcr "MacroTarget='trj1'". 
The error message is as follows:
- ERRoR - Unknowm command, syntax error or undefined Yanaconda variable just before the code in line 1146 of Yanaconda macro './md analyze.mcr': residueslist()=1. If there is no typing mistake, you probably need a newer version of YAARA (or maybe the Twinset)to run this comand. Get an update fram ww.yasara.org/update.The command was: reslistlError 724 occurred, the macro has been stopped.

**Comment by drlemmus** [comment]
Not really an AlphaFill thing but let's have a look. Which type of Yasara do you have, View, Model, Structure or Dynamics?
