### ISSUE TITLE
ctest failures

### ISSUE THREAD

**Issue by meh47336** [PDB-REDO/alphafill#47]
Hello,

I've installed all dependencies which took a while and am now on the ctest step of alphafill.

When I run ctest --test-dir build the first test is successful then the next two (run_process and validation) fail. 

The cause of failure of the second test is that AlphaFill can't seem to find or load the mmcif_pdbx dictionary. I've downloaded and installed mmcif_pdbx. Then I realized from googling that mmcif_pdbx.dic is actually found in libcifpp/rsrc and I confirmed this locally.

Any idea how I can direct alphafill to the dictionary or why it's not detecting it?

Specs:
Rock Linux 9.2
boost 1.78
cmake 3.30
gcc and gxx 11.3.1
make 4.4.1
mmcif-pdbx 2.0.1
libcifpp, libmcfp, and libzeep were cloned and installed today (9/17/24, so should be updated versions)

Thanks for any help,

**Comment by mhekkel** [comment]
Alphafill uses libcifpp. And libcifpp attempts to load the dictionary from a 'resource'. That is, if you use mrc, then this dictionary will be built in in the executable. If you do not use mrc, you will have to install libcifpp first and make sure this is done correctly. Alternatively, you can specify resource locations using an environment variable.

Please read this related documentation: https://www.hekkelman.net/libcifpp-doc/resources.html

**Comment by meh47336** [comment]
I removed libcifpp and performed the installation as described on the libcifpp page. The only difference between this time and last time was using ccmake. Anyway, AlphaFill is now finding everything, is installed, and passing the tests.

Thanks!
