### ISSUE TITLE
Q13315 Issues

### ISSUE THREAD

**Issue by multimeric** [PDB-REDO/alphafill#5]
I'm a bit confused what's happening with Q13315. There might be others with the same issues as well.

So firstly, you do have the structure in AlphaFill: https://alphafill.eu/model?id=Q13315. It has no ligands, but that's okay. What's weird though is that [AlphaFold does *not* have this structure](https://alphafold.ebi.ac.uk/entry/Q13315), and the link from your website to AlphaFold 404s. What's also weird is that your structure mmCIF suggests that it's a 1400-residue protein, whereas [uniprot believes it has 3,056 residues](https://www.uniprot.org/uniprot/Q13315#sequences).

What's going on here? Is it a bug in AlphaFill?

**Comment by multimeric** [comment]
Based on a very small amount of evidence, I think that this 1400-residue model is based on a truncated version of the uniprot sequence, because I think the first 1400 residues are identical. Not sure if you guys or AlphaFold truncated it, or why. Also not sure why AlphaFold doesn't have this protein at all.

**Comment by drlemmus** [comment]
This is something we need to investigate to some extent but 1400 residues is the hard limit of AlphaFold. If the protein is longer it is split up in fragments. They way we deal with this splitting up on our side may not be entirely elegant yet. Thanks for pointing that out.

**Comment by drlemmus** [comment]
"Check if the sequence is currently supported (length between 16 and 2700 amino acids, non-viral, and standard single letter residue codes only). For human proteins, longer sequences are available split into fragments in the [bulk download](https://alphafold.ebi.ac.uk/download)." We got the data from that bulk download.

**Comment by mhekkel** [comment]
We now have proper support for chunked AlphaFold models, see e..g https://alphafill.eu/model?id=Q13315

**Comment by multimeric** [comment]
Great stuff!
