### ISSUE TITLE
important homologs seem to be missing

### ISSUE THREAD

**Issue by esbenfriis** [PDB-REDO/alphafill#6]
Really great tool!

I noticed that alphafill does not always pick up all relevant entries with ligands in the PDB. 
For example, AF-P0DUB9-F1 should find 4LIP and 5LIP which are about 84% identical to P0DUB9 and have relevant ligands.

**Comment by drlemmus** [comment]
AlphaFill uses the PDB-REDO databank which in turn only uses PDB entries that have experimental data. 4lip and 5lip do not have such data. If you can convince the PDB depositors to deposit their experimental data, we are happy to make sure the ligands are transferred.
