### ISSUE TITLE
requirements: issues with setup

### ISSUE THREAD

**Issue by ccbiozhaw** [PDB-REDO/alphafill#9]
Hoi, 

my coworker and I are struggling to get alphafill set up in the first place.  This is the error warning we are stuck with:

![image](https://user-images.githubusercontent.com/80820813/181242145-cef4a477-3ca1-44d5-b3f9-988f398963c3.png)

would it be possible to just have a docker image that we can pull with all requirements set up?

thanks

**Comment by drlemmus** [comment]
Such a docker image would be a no-go. We are working on a feature that lets you run alphafill through alphafill.eu so you have no need for a local installation. That said, the installation procedure should be more streamlined by now so please have another go.

**Comment by steff1088** [comment]
I second the docker image would make the installation much easier and more accessible to users with less computational skills. The list of dependencies to install it locally is a nightmare currently.

**Comment by mhekkel** [comment]
> I second the docker image would make the installation much easier and more accessible to users with less computational skills. The list of dependencies to install it locally is a nightmare currently.

Feel free to contribute such a docker image yourself. Would be very much appreciated. But if you do, keep in mind you need to keep this docker image up to date as well.

**Comment by huiwenke** [comment]
Here is an available docker image for v1.2.1: https://hub.docker.com/r/230218818/alphafill
